bot.token=5677189744:AAGE_1G1OOcucRkNweu45s0Yw66GT_KtMAw
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/accounting?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=GdU_oPhgl4G6d
spring.cache.caffeine.spec=expireAfterAccess=300s
